[bumpversion]
current_version = 2.0.1

[bumpversion:file:pyproject.toml]
search = version = "{current_version}"
replace = version = "{new_version}"

[bumpversion:file:Cargo.toml]
search = version = "{current_version}"
replace = version = "{new_version}"

[bumpversion:file:python/frozndict/__init__.py]
search = __version__ = "{current_version}"
replace = __version__ = "{new_version}"

[bumpversion:file:tests/test_frozndict.py]
search = __version__ == "{current_version}"
replace = __version__ == "{new_version}"
