repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ["--max-line-length=88", "--extend-ignore=E203"]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.5
    hooks:
      - id: pylint
        args: ["--disable=C0114,C0115,C0116,W0212,C0415,E0401,W0621"]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: 🦀 Rust Format Check
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy
        name: 🧹 Rust Clippy
        entry: cargo clippy --features python --tests -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
