[package]
name = "frozendict"
version = "2.1.0"
authors = ["Mahmoud Harmouch <oss@wiseai.dev>"]
edition = "2024"
description = "🧊 A blazingly fast, memory-efficient, immutable dictionary for Python and Node.js, powered by Rust."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wiseaidev/frozndict"
documentation = "https://docs.rs/frozendict"
repository = "https://github.com/wiseaidev/frozndict"
keywords = ["frozendict", "immutable", "dictionary", "hashmap", "napi"]
categories = [
    "data-structures",
    "api-bindings",
    "memory-management",
]
build = "build.rs"
exclude = [
    "/tests",
    ".*",
    "/python",
    "/assets",
    "/benches",
    "/benchmarks",
    "NODE.md",
    "PYTHON.md",
    "package.json",
    "package-lock.json",
    "pyproject.toml",
    "HISTORY.rst",
    "CONTRIBUTING.rst",
]

[lib]
name = "frozendict"
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ahash = { version = "0.8.12", default-features = false, features = ["compile-time-rng"] }
pyo3 = { version = "0.29.2", features = ["extension-module"], optional = true }
napi = { version = "3.12.6", default-features = false, features = ["napi4", "serde-json"], optional = true }
napi-derive = { version = "3.6.7", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }

[build-dependencies]
napi-build = { version = "2.4.3", optional = true }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["std"]
std = ["ahash/std"]
python = ["pyo3", "std"]
node = ["napi", "napi-derive", "napi-build", "serde", "serde_json", "std"]

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
incremental = false
overflow-checks = false

[badges]
maintenance = { status = "actively-developed" }
