[build-system]
requires = ["maturin>=1.14"]
build-backend = "maturin"

[project]
name = "frozndict"
requires-python = ">=3.12"
description = "🧊 A memory-efficient, fully immutable dictionary for Python, powered by Rust."
readme = "README.rst"
license = { text = "MIT" }
authors = [{ name = "Mahmoud Harmouch", email = "oss@wiseai.dev" }]
keywords = ["frozendict", "immutable", "dictionary", "hashmap", "rust"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/wiseaidev/frozndict"
Repository = "https://github.com/wiseaidev/frozndict"
Documentation = "https://docs.rs/frozndict"
Issues = "https://github.com/wiseaidev/frozndict/issues"

[tool.maturin]
features = ["python"]
module-name = "frozndict._frozndict"
python-source = "python"
