name: 🧹 Cargo Clippy Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-clippy:
    name: 🔍 Run Clippy Linter
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v7

      - name: 🦀 Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: 🧪 Run Clippy
        run: cargo clippy --features python --tests -- -D warnings
