name: Publish Multi-Registry

on:
  push:
    tags:
      - "v*"

jobs:
  crates:
    name: Publish to Crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: build
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -m Cargo.toml --features python -o wheels
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels
          password: ${{ secrets.PYPI_TOKEN }}

  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install napi-rs CLI
        run: npm install -g @napi-rs/cli

      - name: Build Node package
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
