name: Publish Multi-Registry

on:
  push:
    tags:
      - "v*"

jobs:
  crates:
    name: Publish to Crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo publish --all-features --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: build
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -m Cargo.toml --features python -o wheels
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels
          password: ${{ secrets.PYPI_TOKEN }}
